---
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    css: style.css
chunk_output_type: console
header-includes:
- \pagenumbering{gobble}
params:
    set_title: "Figure-3"
title: "`r params$set_title`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, autodep = knitr::dep_prev())
```

***

\pagebreak

# Fig 3b


```{r panel3b_cals,echo=T,eval=F,fig.show="hide"}
##Import data
data_dir<-"/media/user/seagate_ICM/AICDA_analysis/Github_repository/" #Set to where you downloaded the data
setwd(data_dir)
source("r/prerequisites.R")
# ICI IMPACT AICDA signature
##Download data from cbioporta: http://www.cbioportal.org/study?id=tmb_mskcc_2018
ICI_IMPACT <- read.delim("/media/user/seagate_ICM/AICDA_analysis/IMPACT/tmb_mskcc_2018/data_mutations_mskcc.txt", 
                         header =  T, 
                         sep = "\t")

library(maftools)
ICI_IMPACT_maf <- read.maf(ICI_IMPACT)

ICI_IMPACT_clinical <- read.delim('/media/user/seagate_ICM/AICDA_analysis/IMPACT/tmb_mskcc_2018/data_clinical_patient.txt',
                                  header = T,
                                  sep = "\t", 
                                  skip = 4)

ICI_IMPACT_sample <- read.delim('/media/user/seagate_ICM/AICDA_analysis/IMPACT/tmb_mskcc_2018/data_clinical_sample.txt',
                                  header = T,
                                  sep = "\t", 
                                  skip = 4)
ICI_IMPACT_clinical_sample <- merge(x = ICI_IMPACT_clinical, y = ICI_IMPACT_sample, by = "PATIENT_ID")

load("r/AICDA_enrich_function_WES_WGS.RData") ## ##Load enrichment function for AICDA 
library( BSgenome.Hsapiens.UCSC.hg19)
ICI_IMPACT_AICDA <- AICDA_enrichment(ICI_IMPACT_maf, ref_genome = "BSgenome.Hsapiens.UCSC.hg19",prefix = 'chr', add = TRUE, background_n = 60)

ICI_IMPACT_AICDA$AICDA_scores$SAMPLE_ID <- ICI_IMPACT_AICDA$AICDA_scores$Tumor_Sample_Barcode

ICI_IMPACT_clinical_sample_common <- subset(ICI_IMPACT_clinical_sample, ICI_IMPACT_clinical_sample$SAMPLE_ID %in% ICI_IMPACT_AICDA$AICDA_scores$Tumor_Sample_Barcode)
ICI_IMPACT_clinical_sample_AICDA <- merge(x = ICI_IMPACT_clinical_sample_common, y = ICI_IMPACT_AICDA$AICDA_scores, by = "SAMPLE_ID")
ICI_IMPACT_clinical_sample_AICDA$censor <- ifelse(ICI_IMPACT_clinical_sample_AICDA$OS_STATUS == "1:DECEASED", 1, 0)
ICI_IMPACT_clinical_sample_AICDA$Cancer_3types<-ifelse(ICI_IMPACT_clinical_sample_AICDA$CANCER_TYPE=="Melanoma","Melanoma",ifelse(ICI_IMPACT_clinical_sample_AICDA$CANCER_TYPE=="Non-Small Cell Lung Cancer","NSCLC","Not_melanoma/NSCLC"))
#ICI_IMPACT_clinical_sample_AICDA$AICDA_90 <- ifelse(ICI_IMPACT_clinical_sample_AICDA$AICDA_Enrichment > 3.5, 1, 0) # decile 90
dim(ICI_IMPACT_clinical_sample_AICDA)
###Graph to see distribution of AICDA mutations
ggboxplot(data = ICI_IMPACT_clinical_sample_AICDA, y ="fraction_AICDA_mutations", x="CANCER_TYPE",color = "SEX")

##Now APOBEC
ICI_IMPACT_APOBEC <- APOBEC_enrichment(ICI_IMPACT_maf, ref_genome = "BSgenome.Hsapiens.UCSC.hg19",prefix = 'chr', add = TRUE)
ICI_IMPACT_clinical_sample_AICDA$fraction_APOBEC_mutations<-ICI_IMPACT_APOBEC$APOBEC_scores$fraction_APOBEC_mutations[match(ICI_IMPACT_clinical_sample_AICDA$SAMPLE_ID,ICI_IMPACT_APOBEC$APOBEC_scores$Tumor_Sample_Barcode)]


###
t<-melt(ICI_IMPACT_clinical_sample_AICDA[],id.vars=c('CANCER_TYPE'), measure.vars=c('fraction_AICDA_mutations','fraction_APOBEC_mutations'))

#Add line global median, add n samples to labels...

impact_p_fractionMuts<-
  ggboxplot(data = t, y ="value", x="CANCER_TYPE",color = "variable",xlab = "Tumor type",ylab = "Fraction of SNP mutations",title = "IMPACT study (n = 1,472)")+theme(axis.text.x = element_text(angle = 90,size=8),axis.title = element_text(face="bold"),plot.title = element_text(hjust = 0.5,face = "bold",size = 15))+ geom_hline(yintercept=mean(ICI_IMPACT_clinical_sample_AICDA$fraction_AICDA_mutations), linetype="dashed",color="#F8766D")+ geom_hline(yintercept=mean(ICI_IMPACT_clinical_sample_AICDA$fraction_APOBEC_mutations), linetype="dashed",color="#00BFC4")+ guides(color=guide_legend(title = "Mutation type"))+scale_color_discrete(labels=c(paste0("AICDA"," (mean = ", round(mean(ICI_IMPACT_clinical_sample_AICDA$fraction_AICDA_mutations),3),")"),paste0("APOBEC"," (mean = ", round(mean(ICI_IMPACT_clinical_sample_AICDA$fraction_APOBEC_mutations),3),")")))+scale_x_discrete(labels=paste0(unique(t$CANCER_TYPE)," (n=", table(ICI_IMPACT_clinical_sample_AICDA$CANCER_TYPE)[unique(t$CANCER_TYPE)],")"))

p_tmp<-ggscatter(data = ICI_IMPACT_clinical_sample_AICDA, title = "All tumors",x = "fraction_APOBEC_mutations",y = "fraction_AICDA_mutations" ,cor.coef = TRUE, cor.coeff.args=list(color="red"),cor.method = "pearson",xlab = "Fraction APOBEC mutations", ylab = "Fraction AICDA mutations",label.rectangle=TRUE, ggtheme=theme_bw(base_size = 14),size = 0.5)+ geom_pointdensity(adjust=4) + scale_color_viridis_c()+geom_smooth(color = "red",method=lm, se=FALSE,linetype="dashed") + theme(plot.margin = unit(c(2,1,1,1), "lines"))+theme(plot.title = element_text(hjust = 0.5))
p_tmp2<-ggscatter(data = ICI_IMPACT_clinical_sample_AICDA, x = "fraction_APOBEC_mutations",y = "fraction_AICDA_mutations" ,facet.by = 'CANCER_TYPE',cor.coef = TRUE, cor.coeff.args=list(color="red"),cor.method = "pearson",xlab = "Fraction APOBEC mutations", ylab = "Fraction AICDA mutations",label.rectangle=TRUE, ggtheme=theme_bw(base_size = 14),size = 0.5)+ geom_pointdensity(adjust=4) + scale_color_viridis_c()+geom_smooth(color = "red",method=lm, se=FALSE,linetype="dashed") + theme(plot.margin = unit(c(2,1,1,1), "lines"))+theme(plot.title = element_text(hjust = 0.5))

p_tmp3<-ggarrange(p_tmp,p_tmp2,ncol = 1,nrow = 2,align = "hv",heights = c(1,3))

ggsave(p_tmp3,filename = "/media/user/seagate_ICM/AICDA_analysis/IMPACT/Spearman_AICDA_APOBEC_fraction_IMPACT_ICI.pdf",width = 16,height = 14)



library(dplyr)
mydata <- ICI_IMPACT_clinical_sample_AICDA %>%
  group_by(CANCER_TYPE) %>%
  mutate(decile = ntile(fraction_AICDA_mutations, 10)) %>%
  ungroup() # decile by type of cancer

mydata$decile_5AICDA <- ifelse(mydata$decile >= 5, 1, 0) #Median within each histology

mydata$frac_median <- ifelse(mydata$fraction_AICDA_mutations > median(mydata$fraction_AICDA_mutations), 1,0) #Global median

###Use global median, since within each histology does not work for the MIao cohort (low number of samples)


library(survival)
library(survminer)

fit <- survfit(Surv(OS_MONTHS, censor) ~ frac_median, data = mydata)



ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "AICDA mutation's median fraction and survival after immunotherapy across multiple cancer types",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ frac_median, data = mydata, subset = mydata$SEX == "Male")


ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "AICDA mutation's median fraction and survival after immunotherapy across multiple cancer types, in males",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ frac_median, data = mydata, subset = mydata$SEX == "Female")

ggsurvplot(fit, data = mydata)

ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "AICDA mutation's median fraction and survival after immunotherapy across multiple cancer types, in females",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

####Now do for apobec
load("/media/aalentorn/home2/projets_en_cours/AICDA_pancancer/APOBEC_enrich_function.RData")
ICI_IMPACT_APOBEC <- APOBEC_enrichment(ICI_IMPACT_maf,ref_genome = "BSgenome.Hsapiens.UCSC.hg19",prefix = 'chr', add = TRUE)
ICI_IMPACT_APOBEC$APOBEC_scores$SAMPLE_ID <- ICI_IMPACT_APOBEC$APOBEC_scores$Tumor_Sample_Barcode

ICI_IMPACT_clinical_sample_AICDA <- merge(x = ICI_IMPACT_clinical_sample_AICDA, y = ICI_IMPACT_APOBEC$APOBEC_scores, by = "SAMPLE_ID")


library(dplyr)

mydata <- ICI_IMPACT_clinical_sample_AICDA %>%
  group_by(CANCER_TYPE) %>%
  mutate(decile = ntile(fraction_APOBEC_mutations, 10)) %>%
  ungroup() # decile by type of cancer

mydata$decile_5APOBEC <- ifelse(mydata$decile >= 5, 1, 0)

mydata$frac_median_APOBEC <- ifelse(mydata$fraction_APOBEC_mutations > median(mydata$fraction_APOBEC_mutations), 1,0) #Global median


mydata <- mydata %>%
  group_by(CANCER_TYPE) %>%
  mutate(decile = ntile(fraction_AICDA_mutations, 10)) %>%
  ungroup() # decile by type of cancer

mydata$decile_5AICDA <- ifelse(mydata$decile >= 5, 1, 0)


mydata$frac_median <- ifelse(mydata$fraction_AICDA_mutations > median(mydata$fraction_AICDA_mutations), 1,0) #Global median



library(survival)
library(survminer)

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_5APOBEC, data = mydata)

ggsurvplot(fit, data = mydata)

ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "APOBEC mutation's fraction and survival after immunotherapy across multiple cancer types",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_5APOBEC, data = mydata, subset = mydata$SEX == "Male")


ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "APOBEC enrichment and survival after immunotherapy across multiple cancer types, in males",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_5APOBEC, data = mydata, subset = mydata$SEX == "Female")



ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "APOBEC enrichment and survival after immunotherapy across multiple cancer types, in females",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)


###For TMB_score

mydata <- mydata %>%
  group_by(CANCER_TYPE) %>%
  mutate(decile = ntile(TMB_SCORE, 10)) %>%
  ungroup() # decile by type of cancer

mydata$decile_TMB20 <- ifelse(mydata$decile >= 8, 1, 0) #Separate using the top 20% as reported in the original study

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_TMB20, data = mydata)



ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "TMB 20% and survival after immunotherapy across multiple cancer types",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_TMB20, data = mydata, subset = mydata$SEX == "Male")


ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "TMB and survival after immunotherapy across multiple cancer types, in males",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

fit <- survfit(Surv(OS_MONTHS, censor) ~ decile_TMB20, data = mydata, subset = mydata$SEX == "Female")


ggsurvplot(
  fit,
  data = mydata,
  size = 1,                 # change line size
  title = "TMB and survival after immunotherapy across multiple cancer types, in females",
  #palette =
  #  c("#E7B800", "#2E9FDF"),# custom color palettes
  #conf.int = TRUE,          # Add confidence interval
  pval = TRUE,              # Add p-value
  risk.table = TRUE,        # Add risk table
  risk.table.col = "strata",# Risk table color by groups
  legend.labs =
    c("Low", "High"),    # Change legend labels
  risk.table.height = 0.25, # Useful to change when you have multiple groups
  ggtheme = theme_bw()      # Change ggplot2 theme
)

######Now do multivariate analysis

res.cox <- coxph(Surv(OS_MONTHS, censor) ~ decile_TMB20 + AGE_GROUP + DRUG_TYPE + decile_5APOBEC + frac_median + CANCER_TYPE , data = mydata)
summary(res.cox)

##Taking out APOBEC
res.cox <- coxph(Surv(OS_MONTHS, censor) ~ decile_TMB20 + AGE_GROUP + SEX  + frac_median  , data = mydata)
res.cox <- coxph(Surv(OS_MONTHS, censor) ~ decile_TMB20 + AGE_GROUP + SEX  + frac_median  + frac_median_APOBEC , data = mydata)
summary(res.cox)
##SIgnificant for AICDA

###Do graph to aggrupate values and do forestplot


#####
####
####Extract dat from the cox.model and graph using forestplot, must extract the HR along with the CI



```

```{r panel_3b, fig.width=16,fig.height=14}
##Import data
data_dir<-"/media/user/seagate_ICM/AICDA_analysis/Github_repository/" #Set to where you downloaded the data
setwd(data_dir)
source("r/prerequisites.R")
##Import clinical data with needed calculated variables
mydata<-as.data.table(read.delim("Data/Figure3/Figure3b_c.tab"))

library(scales)
scientific <- function(x){
    ifelse(x==0, "0", parse(text=gsub("[+]", "", gsub("e", " %*% 10^", scientific_format()(x)))))
}

res.cox <- coxph(Surv(OS_MONTHS, censor) ~ decile_TMB20 + AGE_GROUP + SEX  + frac_median  + frac_median_APOBEC , data = mydata)

res_coxph<-summary(res.cox)
res_coxph<-as.data.frame(res_coxph$conf.int)

res_coxph_data<-data.frame(mean=c(NA,NA,NA,res_coxph$`exp(coef)`[1],res_coxph$`exp(coef)`[c(7,8)],NA,NA,res_coxph$`exp(coef)`[2:5],NA,NA,res_coxph$`exp(coef)`[6]),lower=c(NA,NA,NA,res_coxph$`lower .95`[1],res_coxph$`lower .95`[c(7,8)],NA,NA,res_coxph$`lower .95`[2:5],NA,NA,res_coxph$`lower .95`[6]),upper=c(NA,NA,NA,res_coxph$`upper .95`[1],res_coxph$`upper .95`[c(7,8)],NA,NA,res_coxph$`upper .95`[2:5],NA,NA,res_coxph$`upper .95`[6]),row.names = c("","2","Variable","Binary (TMB Top 20% of each histology)","Binary (AICDA mutations Top 50% of all histology)","Binary (APOBEC mutations Top 50% of all histology)","3","<30 (reference)","31-50","50-60","61-70",">71","4","Female (reference)","Male"))

mean_cox<-as.character(round(res_coxph_data$mean,3))
CI_cox<-paste0(as.character(round(res_coxph_data$lower,3)),"-",as.character(round(res_coxph_data$upper,3)))
CI_cox[which(CI_cox=="NA-NA")]<-NA
pval_cox<-scientific(round(summary(res.cox)$coefficients[,5],10))
pval_cox<-c(list(NA,NA,pval_cox[1]),list(pval_cox[7]),list(pval_cox[8]),NA,NA,list(pval_cox[3]),list(pval_cox[4]),list(pval_cox[5]),list(pval_cox[2]),NA,NA,list(pval_cox[6]))

tabletext<-list(c("","Variables","Mutations","Binary (TMB Top 20% of each histology)","Binary (AICDA mutations Top 50% of all histologies)","Binary (APOBEC mutations Top 50% of all histologies)","Age Group","<30 (reference)","31-50","50-60","61-70",">71","Sex","Female (reference)","Male"),c("HR",mean_cox[-(1)]),c("95% CI",CI_cox[-(1)]),c("P value",pval_cox[]))
  ##This is to add the text manually
  
forestplot(tabletext, title = "Cox-P Multivariate analysis (n = 1472)",
           res_coxph_data,new_page = TRUE,
           is.summary=c(TRUE,TRUE,TRUE,rep(FALSE,3),TRUE,rep(FALSE,5),TRUE,rep(FALSE,2)), ##TRUE set fonds differently
           #clip=c(0.1,2.5), 
           xlog=TRUE,  hrzl_lines = list("4" = gpar(lty=1,lwd=1,columns=1), "8" = gpar(lwd=1,columns=1),"14" = gpar(lwd=1,columns=1),"7" = gpar(lty=2,columns=1:4),"12" = gpar(lwd=2,columns=1:4), "3" = gpar(lwd=2, col = "#000044"),"1" = gpar(lwd=3, col = "#000044"),"2" = gpar(lwd=2, col = "#000044")),
           col=fpColors(box="royalblue",line="darkblue", summary="royalblue"),xlab="<--Better OS-----Hazard Ratio----- Worse OS-->",vertices = TRUE,boxsize = 0.2,xticks = c(.5, 0.75, 1, 1.5,2),graphwidth = unit(90, "mm"),txt_gp=fpTxtGp(xlab  = gpar(cex = .8), ticks=gpar(cex=.8)))

CIC_alltumor_coxP_2<-recordPlot()


```

***

\pagebreak

# Fig 3c


```{r panel3c_cals,echo=T,eval=T,fig.show="hide"}

data_dir<-"/media/user/seagate_ICM/AICDA_analysis/Github_repository/" #Set to where you downloaded the data
setwd(data_dir)
source("r/prerequisites.R")
##Import clinical data with needed calculated variables
mydata<-as.data.table(read.delim("Data/Figure3/Figure3b_c.tab"))

library(scales)
scientific <- function(x){
    ifelse(x==0, "0", parse(text=gsub("[+]", "", gsub("e", " %*% 10^", scientific_format()(x)))))
}

###Create empty data frame for the values for AICDA and TMB, APOBEC, exclude "Skin Cancer, Non-Melanoma"
res_coxph_byTumor_AICDA<-as.data.frame(matrix(data = NA,ncol = 6, nrow = 11,dimnames = list(c("All samples in cohort",unique(mydata$CANCER_TYPE)[1:10]),c("Mean","lower","upper","p_val","cut_off","N"))))
res_coxph_byTumor_TMB<-as.data.frame(matrix(data = NA,ncol = 6, nrow = 11,dimnames = list(c("All samples in cohort",unique(mydata$CANCER_TYPE)[1:10]),c("Mean","lower","upper","p_val","cut_off","N"))))
res_coxph_byTumor_APO<-as.data.frame(matrix(data = NA,ncol = 6, nrow = 11,dimnames = list(c("All samples in cohort",unique(mydata$CANCER_TYPE)[1:10]),c("Mean","lower","upper","p_val","cut_off","N"))))

#making formulas
univ_formulas <- sapply(c("decile_TMB20","frac_median","frac_median_APOBEC"),function(x)as.formula(paste('Surv(OS_MONTHS,censor)~',x))
)
###Predefined for text
tabletext_bytumor<-list(c("","Variables","Cancer Type/Mutations"),c("HR","",""),c("95% CI","",""),c("No. of Patients","",""),c("Cutoff","",""),c("P value","",""))

res_coxph_byTumor_both<-res_coxph_byTumor_AICDA[1:3,];res_coxph_byTumor_both[1:3,]<-NA;

for (i in 1:10) {

    univ_results<-summary(coxph(Surv(OS_MONTHS, censor) ~ frac_median  , data = mydata))
    res_coxph_byTumor_AICDA[1,1:3]<-univ_results$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_AICDA$p_val[1]<-univ_results$coefficients[5]
  res_coxph_byTumor_AICDA$N[1]<-univ_results$n
  #res_coxph_byTumor_AICDA$cut_off[i]<-quantile(mydata$fraction_AICDA_mutations[mydata$CANCER_TYPE %in% unique(mydata$CANCER_TYPE)[i]], probs = seq(0,1,0.1))[6]##Calculate cutoff in case of within histology
  res_coxph_byTumor_AICDA$cut_off[1]<-median(mydata$fraction_AICDA_mutations)
  ###Repeat for APOBEC
  univ_results<-summary(coxph(Surv(OS_MONTHS, censor) ~ frac_median_APOBEC  , data = mydata))
    res_coxph_byTumor_APO[1,1:3]<-univ_results$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_APO$p_val[1]<-univ_results$coefficients[5]
  res_coxph_byTumor_APO$N[1]<-univ_results$n
  #res_coxph_byTumor_AICDA$cut_off[i]<-quantile(mydata$fraction_AICDA_mutations[mydata$CANCER_TYPE %in% unique(mydata$CANCER_TYPE)[i]], probs = seq(0,1,0.1))[6]##Calculate cutoff in case of within histology
  res_coxph_byTumor_APO$cut_off[1]<-median(mydata$fraction_APOBEC_mutations)
  
   ###Repeat for TMB
   univ_results<-summary(coxph(Surv(OS_MONTHS, censor) ~ decile_TMB20   , data = mydata))
  res_coxph_byTumor_TMB[1,1:3]<-univ_results$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_TMB$p_val[1]<-univ_results$coefficients[5]
  res_coxph_byTumor_TMB$N[1]<-univ_results$n
  res_coxph_byTumor_TMB$cut_off[1]<-NA #Because it was per histology
  
   #making a list of models
univ_models <- lapply(univ_formulas, function(x){coxph(x,data=subset(mydata,CANCER_TYPE %in% unique(mydata$CANCER_TYPE)[i]))})

#extract data (here I've gone for HR and confint)
univ_results <- lapply(univ_models,function(x){return(summary(x))})

res_coxph_byTumor_AICDA[i+1,1:3]<-univ_results$frac_median$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_AICDA$p_val[i+1]<-univ_results$frac_median$coefficients[5]
  res_coxph_byTumor_AICDA$N[i+1]<-univ_results$frac_median$n
  #res_coxph_byTumor_AICDA$cut_off[i+1]<-quantile(mydata$fraction_AICDA_mutations[mydata$CANCER_TYPE %in% unique(mydata$CANCER_TYPE)[i]], probs = seq(0,1,0.1))[6]##Calculate cutoff in case of within histology
  res_coxph_byTumor_AICDA$cut_off[i+1]<-median(mydata$fraction_AICDA_mutations)
  ###APOBEC
  res_coxph_byTumor_APO[i+1,1:3]<-univ_results$frac_median_APOBEC$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_APO$p_val[i+1]<-univ_results$frac_median_APOBEC$coefficients[5]
  res_coxph_byTumor_APO$N[i+1]<-univ_results$frac_median$n
 
  res_coxph_byTumor_APO$cut_off[i+1]<-median(mydata$fraction_APOBEC_mutations)
  
  ###Repeat for TMB
  res_coxph_byTumor_TMB[i+1,1:3]<-univ_results$decile_TMB20$conf.int[c(1,3,4)] #get mean, upper and lower values CI
res_coxph_byTumor_TMB$p_val[i+1]<-univ_results$decile_TMB20$coefficients[5]
  res_coxph_byTumor_TMB$N[i+1]<-univ_results$decile_TMB20$n
  res_coxph_byTumor_TMB$cut_off[i+1]<-quantile(mydata$TMB_SCORE[mydata$CANCER_TYPE %in% unique(mydata$CANCER_TYPE)[i]], probs = seq(0,1,0.1))[9]##Calculate cutoff
  ###Repeat for TMB but using the top 20%
  ###Now make table for text
  pval_cox<-scientific(round(summary(res.cox)$coefficients[,5],10))
pval_cox<-c(list(NA,NA,pval_cox[1]),list(pval_cox[7]),NA,NA,list(pval_cox[3]),list(pval_cox[4]),list(pval_cox[5]),list(pval_cox[2]),NA,NA,list(pval_cox[6]))

tabletext_bytumor<-list(c(tabletext_bytumor[[1]],paste0(rownames(res_coxph_byTumor_AICDA)[i],"/TMB"),paste0(rownames(res_coxph_byTumor_AICDA)[i],"/AICDA"),paste0(rownames(res_coxph_byTumor_AICDA)[i],"/APOBEC")),c(tabletext_bytumor[[2]],as.character(round(res_coxph_byTumor_TMB$Mean[i],3)),as.character(round(res_coxph_byTumor_AICDA$Mean[i],3)),as.character(round(res_coxph_byTumor_APO$Mean[i],3))),c(tabletext_bytumor[[3]],paste0(as.character(round(res_coxph_byTumor_TMB$lower[i],3)),"-",as.character(round(res_coxph_byTumor_TMB$upper[i],3))),paste0(as.character(round(res_coxph_byTumor_AICDA$lower[i],3)),"-",as.character(round(res_coxph_byTumor_AICDA$upper[i],3))),paste0(as.character(round(res_coxph_byTumor_APO$lower[i],3)),"-",as.character(round(res_coxph_byTumor_APO$upper[i],3)))),c(tabletext_bytumor[[4]],as.character(round(res_coxph_byTumor_TMB$N[i],3)),as.character(res_coxph_byTumor_AICDA$N[i]),as.character(res_coxph_byTumor_APO$N[i])),c(tabletext_bytumor[[5]],as.character(round(res_coxph_byTumor_TMB$cut_off[i],3)),as.character(round(res_coxph_byTumor_AICDA$cut_off[i],3)),as.character(round(res_coxph_byTumor_APO$cut_off[i],3))),c(tabletext_bytumor[[6]],list(scientific(round(res_coxph_byTumor_TMB$p_val[i],10)),scientific(round(res_coxph_byTumor_AICDA$p_val[i],10)),scientific(round(res_coxph_byTumor_APO$p_val[i],10)))))
  


  ##Merge values
res_coxph_byTumor_both<-rbind(res_coxph_byTumor_both[],res_coxph_byTumor_TMB[i,],res_coxph_byTumor_AICDA[i,],res_coxph_byTumor_APO[i,])

if(i==10){
  tabletext_bytumor<-list(c(tabletext_bytumor[[1]],paste0(rownames(res_coxph_byTumor_AICDA)[i+1],"/TMB"),paste0(rownames(res_coxph_byTumor_AICDA)[i+1],"/AICDA"),paste0(rownames(res_coxph_byTumor_APO)[i+1],"/APOBEC")),c(tabletext_bytumor[[2]],as.character(round(res_coxph_byTumor_TMB$Mean[i+1],3)),as.character(round(res_coxph_byTumor_AICDA$Mean[i+1],3)),as.character(round(res_coxph_byTumor_APO$Mean[i+1],3))),c(tabletext_bytumor[[3]],paste0(as.character(round(res_coxph_byTumor_TMB$lower[i+1],3)),"-",as.character(round(res_coxph_byTumor_TMB$upper[i+1],3))),paste0(as.character(round(res_coxph_byTumor_AICDA$lower[i+1],3)),"-",as.character(round(res_coxph_byTumor_AICDA$upper[i+1],3))),paste0(as.character(round(res_coxph_byTumor_APO$lower[i+1],3)),"-",as.character(round(res_coxph_byTumor_APO$upper[i+1],3)))),c(tabletext_bytumor[[4]],as.character(round(res_coxph_byTumor_TMB$N[i+1],3)),as.character(res_coxph_byTumor_AICDA$N[i+1]),as.character(res_coxph_byTumor_APO$N[i+1])),c(tabletext_bytumor[[5]],as.character(round(res_coxph_byTumor_TMB$cut_off[i+1],3)),as.character(round(res_coxph_byTumor_AICDA$cut_off[i+1],3)),as.character(round(res_coxph_byTumor_APO$cut_off[i+1],3))),c(tabletext_bytumor[[6]],list(scientific(round(res_coxph_byTumor_TMB$p_val[i+1],10)),scientific(round(res_coxph_byTumor_AICDA$p_val[i+1],10)),scientific(round(res_coxph_byTumor_APO$p_val[i+1],10)))))
  res_coxph_byTumor_both<-rbind(res_coxph_byTumor_both[],res_coxph_byTumor_TMB[i+1,],res_coxph_byTumor_AICDA[i+1,],res_coxph_byTumor_APO[i+1,])

}
}

##Add 
style<-fpShapesGp( default = gpar( col="black"),lines = list(gpar(col = "blue"),gpar(col = "blue"),gpar(col = "blue"),gpar(col = "red"),gpar(col = "red"),gpar(col = "red"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "red"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "red"),gpar(col = "red"),gpar(col = "red"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "blue"),gpar(col = "black"),gpar(col = "cornflowerblue"),gpar(col = "red"),gpar(col = "red"),gpar(col = "red")),
    box = list(gpar(fill = "blue"),gpar(fill = "blue"),gpar(fill = "blue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue"),gpar(fill = "blue"),gpar(fill = "black"),gpar(fill = "cornflowerblue")))


forestplot(tabletext_bytumor, title = "Cox-P Multivariate analysis (n = 1472)",
           res_coxph_byTumor_both[,1:3],new_page = TRUE,
           graph.pos = 5,
           is.summary=c(TRUE,TRUE,TRUE,rep(FALSE,33)), ##TRUE set fonds differently
           #clip=c(0.1,2.5), 
           xlog=TRUE,  hrzl_lines = list("4" = gpar(lty=1,lwd=1,columns=1), "7" = gpar(lty=2,columns=c(1:4,6:7)),"10" = gpar(lty=2,columns=c(1:4,6:7)),"13" = gpar(lty=2,columns=c(1:4,6:7)),"16" = gpar(lty=2,columns=c(1:4,6:7)), "19" = gpar(lty=2,columns=c(1:4,6:7)),"22" = gpar(lty=2,columns=c(1:4,6:7)),"25" = gpar(lty=2,columns=c(1:4,6:7)),"28" = gpar(lty=2,columns=c(1:4,6:7)),"31" = gpar(lty=2,columns=c(1:4,6:7)),"34" = gpar(lty=2,columns=c(1:4,6:7)),"3" = gpar(lwd=2, col = "#000044"),"1" = gpar(lwd=3, col = "#000044"),"2" = gpar(lwd=2, col = "#000044")),
           col=fpColors(box=c("blue"),line="darkblue", summary="royalblue"),xlab="<--Better OS-----Hazard Ratio----- Worse OS-->",vertices = TRUE,boxsize = 0.4,
           fn.ci_norm=c(rep("fpDrawCircleCI",3),rep(c("fpDrawCircleCI","fpDrawDiamondCI","fpDrawDiamondCI"),11)),
           #xticks = c(0,.25,.5, 0.75, 1, 1.5,2,2.5,3),
           graphwidth = unit(150, "mm"),txt_gp=fpTxtGp(xlab  = gpar(cex = .8), ticks=gpar(cex=.8)),shapes_gp = style)


###Manually add legend
###Generate artificially
tmp<-grid.grab()
plot.new()

legend(x =.43 ,y=.95, legend=c("TMB","AICDA","APOBEC","Significant"),col=c("blue","black","cornflowerblue","red"),box.lty=1,pch=c(19,23,23,NA),lty=1,pt.bg=c("blue","black","cornflowerblue",NA),pt.cex=1, cex=.6,title="Mutations",bg="#F9F9F9",box.col="#CCCCCC",seg.len=1,text.width=.025) 

pushViewport(viewport(height = 1,width = 1.2))
grid.draw(tmp)

CIC_bytumor_coxP_2<-recordPlot()


CIC_bytumor_coxP_2

```

```{r panel_5D, fig.width=18,fig.height=14}
CIC_bytumor_coxP_2
```


***

\pagebreak
